In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('doencas_coracao.csv')

In [3]:
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [16]:
df.shape

(299, 13)

In [17]:
df.loc[df['DEATH_EVENT'] == 1].describe()

age    anaemia  creatinine_phosphokinase   diabetes  \
count  96.000000  96.000000                 96.000000  96.000000   
mean   65.215281   0.479167                670.197917   0.416667   
std    13.214556   0.502188               1316.580640   0.495595   
min    42.000000   0.000000                 23.000000   0.000000   
25%    55.000000   0.000000                128.750000   0.000000   
50%    65.000000   0.000000                259.000000   0.000000   
75%    75.000000   1.000000                582.000000   1.000000   
max    95.000000   1.000000               7861.000000   1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count          96.000000             96.00000      96.000000   
mean           33.468750              0.40625  256381.044792   
std            12.525303              0.49371   98525.682856   
min            14.000000              0.00000   47000.000000   
25%            25.000000              0.00000  197500.000000   
50%            30.000000              0.00000  258500.000000   
75%            38.000000              1.00000  311000.000000   
max            70.000000              1.00000  621000.000000   

       serum_creatinine  serum_sodium        sex    smoking        time  \
count         96.000000     96.000000  96.000000  96.000000   96.000000   
mean           1.835833    135.375000   0.645833   0.312500   70.885417   
std            1.468562      5.001579   0.480771   0.465946   62.378281   
min            0.600000    116.000000   0.000000   0.000000    4.000000   
25%            1.075000    133.000000   0.000000   0.000000   25.500000   
50%            1.300000    135.500000   1.000000   0.000000   44.500000   
75%            1.900000    138.250000   1.000000   1.000000  102.250000   
max            9.400000    146.000000   1.000000   1.000000  241.000000   

       DEATH_EVENT  
count         96.0  
mean           1.0  
std            0.0  
min            1.0  
25%            1.0  
50%            1.0  
75%            1.0  
max            1.0

In [21]:
df.loc[(df['DEATH_EVENT'] == 1) & (df['sex'] == 0)].count()

age                         34
anaemia                     34
creatinine_phosphokinase    34
diabetes                    34
ejection_fraction           34
high_blood_pressure         34
platelets                   34
serum_creatinine            34
serum_sodium                34
sex                         34
smoking                     34
time                        34
DEATH_EVENT                 34
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
age                         299 non-null float64
anaemia                     299 non-null int64
creatinine_phosphokinase    299 non-null int64
diabetes                    299 non-null int64
ejection_fraction           299 non-null int64
high_blood_pressure         299 non-null int64
platelets                   299 non-null float64
serum_creatinine            299 non-null float64
serum_sodium                299 non-null int64
sex                         299 non-null int64
smoking                     299 non-null int64
time                        299 non-null int64
DEATH_EVENT                 299 non-null int64
dtypes: float64(3), int64(10)
memory usage: 30.4 KB


In [34]:
# classes
X = df.iloc[:,:-1].values
y = df.iloc[:,12].values
X


array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.000e+00, 0.000e+00,
        4.000e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 1.000e+00, 0.000e+00,
        6.000e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.000e+00, 1.000e+00,
        7.000e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 0.000e+00,
        2.780e+02],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.000e+00, 1.000e+00,
        2.800e+02],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.000e+00, 1.000e+00,
        2.850e+02]])

### Normalizando dados

In [35]:

from sklearn.preprocessing import MinMaxScaler

normaliza = MinMaxScaler()
entradas_normalizadas = normaliza.fit_transform(X)

In [37]:
# Train Test Split
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(entradas_normalizadas, y, test_size = 0.30, random_state = 42)

In [40]:
test_labels

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0], dtype=int64)

### Algoritmo KNN

In [38]:

from sklearn.neighbors import KNeighborsClassifier

clf_KNN = KNeighborsClassifier(n_neighbors=5)
clf_KNN.fit(train_data, train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [41]:
#realiza a previsão
predicoes = clf_KNN.predict(test_data)

In [42]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels, predicoes))
print(classification_report(test_labels, predicoes))

# acuracia TP / total = 0,61

[[51  2]
 [33  4]]
              precision    recall  f1-score   support

           0       0.61      0.96      0.74        53
           1       0.67      0.11      0.19        37

   micro avg       0.61      0.61      0.61        90
   macro avg       0.64      0.54      0.47        90
weighted avg       0.63      0.61      0.51        90



### Algoritmo Árvore de Decisão

In [44]:
from sklearn.tree import DecisionTreeClassifier # importa o classificador árvore de decisão
from sklearn import metrics #importa as métricas para avaliação

clf_arvore = DecisionTreeClassifier(random_state=1)

# Realiza o treinamento do classificador
clf_arvore = clf_arvore.fit(train_data, train_labels)

#Realiza a previsão de classificaçao 
predDecisionTree = clf_arvore.predict(test_data)

In [45]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels, predDecisionTree))
print(classification_report(test_labels, predDecisionTree))

[[42 11]
 [19 18]]
              precision    recall  f1-score   support

           0       0.69      0.79      0.74        53
           1       0.62      0.49      0.55        37

   micro avg       0.67      0.67      0.67        90
   macro avg       0.65      0.64      0.64        90
weighted avg       0.66      0.67      0.66        90



### Algoritmo Rede MLP

In [46]:


#definição da biblioteca
from sklearn.neural_network import MLPClassifier

clf_mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,
10), random_state=1)

#realiza o fit do modelo
clf_mlp.fit(train_data, train_labels)

#realiza a previsão
y_pred=clf_mlp.predict(test_data)

In [47]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels, y_pred))
print(classification_report(test_labels, y_pred))

[[48  5]
 [14 23]]
              precision    recall  f1-score   support

           0       0.77      0.91      0.83        53
           1       0.82      0.62      0.71        37

   micro avg       0.79      0.79      0.79        90
   macro avg       0.80      0.76      0.77        90
weighted avg       0.79      0.79      0.78        90



### Concorrência

In [60]:
def contador():
    x = 100000
    while x > 0:
        x -= 1

In [61]:
def imple_sequencial():
    contador()
    contador()

In [62]:
import threading

def imple_concorrente():
    thread_1 = threading.Thread(target=contador)
    thread_2 = threading.Thread(target=contador)

In [63]:
import time
import random

t0 = time.time()

imple_sequencial()

#calcula o tempo de execução
t1 = time.time()
totalTime = t1 - t0
print("Tempo total de execução 1 {}".format(totalTime))


time.sleep(random.randint(1,20))

t0 = time.time()

imple_concorrente()

#calcula o tempo de execução
t1 = time.time()
totalTime = t1 - t0
print("Tempo total de execução 2 {}".format(totalTime))

Tempo total de execução 1 0.06187915802001953
Tempo total de execução 2 0.0


In [53]:
# observer
import rx
import rx.operators as ops

source = rx.from_iterable([5,4,3,2,1]) # streaming
disposable = source.pipe().subscribe(
    on_next = lambda i : print("on_next: {}".format(i)),
    on_completed = lambda: print("on_completed"),
    on_error = lambda e : print("on_error: {}".format(e))
) #inscrição do observer

disposable.dispose()
print("Fim")

on_next: 5
on_next: 4
on_next: 3
on_next: 2
on_next: 1
on_completed
Fim


### PyGame

In [65]:
!pip install pygame

In [ ]:
import pygame
from pygame.locals import *
from sys import exit

pygame.init()

screen = pygame.display.set_mode((720, 640))
pygame.display.set_caption("Desafio-Módulo 4")

while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            exit()
            
        screen.fill((255,0,255))
        
        x, y = pygame.mouse.get_pos()
        
        print(x,y)
        
    pygame.display.update()

pygame 2.0.1 (SDL 2.0.14, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
