### DIABETES - Regressão

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dfDiabetes = pd.read_csv("diabetes_numeric.csv")

In [4]:
dfDiabetes.head(10)

age  deficit  c_peptide
0   5.2     -8.1        4.8
1   8.8    -16.1        4.1
2  10.5     -0.9        5.2
3  10.6     -7.8        5.5
4  10.4    -29.0        5.0
5   1.8    -19.2        3.4
6  12.7    -18.9        3.4
7  15.6    -10.6        4.9
8   5.8     -2.8        5.6
9   1.9    -25.0        3.7

In [7]:
dfDiabetes.shape

(43, 3)

In [8]:
dfDiabetes.describe()

age    deficit  c_peptide
count  43.000000  43.000000  43.000000
mean    9.032558  -8.148837   4.746512
std     4.022539   7.123080   0.720565
min     0.900000 -29.000000   3.000000
25%     5.500000 -12.700000   4.450000
50%    10.400000  -7.800000   4.900000
75%    11.850000  -2.000000   5.100000
max    15.600000  -0.200000   6.600000

In [9]:
dfDiabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 3 columns):
age          43 non-null float64
deficit      43 non-null float64
c_peptide    43 non-null float64
dtypes: float64(3)
memory usage: 1.1 KB


In [10]:
labelDiabetes = np.array(dfDiabetes['c_peptide'])

dfDiabetes = dfDiabetes.drop('c_peptide', axis=1)
dataDiabetes = np.array(dfDiabetes)

In [11]:
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(dataDiabetes, labelDiabetes, test_size = 0.25, random_state = 42)

In [12]:
# importar o modelo de regressão linear
from sklearn.linear_model import LinearRegression 

# treinando o modelo no conjunto de dados de treino
regression = LinearRegression().fit(train_data, train_labels);

In [13]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions1_labels = regression.predict(test_data)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels, 'Previsto': predictions1_labels})  
p.head(10)

Real  Previsto
0   6.0  5.256343
1   5.7  5.355738
2   5.1  5.118052
3   5.1  4.716996
4   3.9  4.348632
5   4.1  4.750498
6   5.0  4.056830
7   4.8  4.413207
8   5.6  4.656556
9   5.5  4.820646

In [15]:
# importar biblioteca para calculo de métricas
from sklearn import metrics  

#avaliando o modelo
print('R2:', metrics.r2_score(test_labels, predictions1_labels)) 
print('MSE:', metrics.mean_squared_error(test_labels, predictions1_labels))  
print('MAE:', metrics.mean_absolute_error(test_labels, predictions1_labels))

R2: 0.21880597788432854
MSE: 0.4745269473181972
MAE: 0.6107422323514549


## BLOODTRANSF - SVC

In [23]:
dfBlood = pd.read_csv("bloodtransf.csv")

In [24]:
dfBlood.head(10)

V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1
5   4   4   1000   4      1
6   2   7   1750  14      2
7   1  12   3000  35      1
8   2   9   2250  22      2
9   5  46  11500  98      2

In [25]:
dfBlood.shape

(748, 5)

In [26]:
dfBlood.describe()

V1          V2            V3          V4       Class
count  748.000000  748.000000    748.000000  748.000000  748.000000
mean     9.506684    5.514706   1378.676471   34.282086    1.237968
std      8.095396    5.839307   1459.826781   24.376714    0.426124
min      0.000000    1.000000    250.000000    2.000000    1.000000
25%      2.750000    2.000000    500.000000   16.000000    1.000000
50%      7.000000    4.000000   1000.000000   28.000000    1.000000
75%     14.000000    7.000000   1750.000000   50.000000    1.000000
max     74.000000   50.000000  12500.000000   98.000000    2.000000

In [27]:
dfBlood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
V1       748 non-null int64
V2       748 non-null int64
V3       748 non-null int64
V4       748 non-null int64
Class    748 non-null int64
dtypes: int64(5)
memory usage: 29.3 KB


In [28]:
labelBlood = np.array(dfBlood['Class'])

dfBlood = dfBlood.drop('Class', axis=1)
dataBlood = np.array(dfBlood)

In [29]:
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(dataBlood, labelBlood, test_size = 0.25, random_state = 42)

In [30]:
#importar o modelo SVM
from sklearn.svm import SVC

# instanciacao e determinacao dos hiperparâmetros do SVM: tipo de kernel
classifier = SVC(kernel='rbf')

# treinando o SVM
classifier.fit(train_data,train_labels)

D:\Users\elain\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [31]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions2_labels = classifier.predict(test_data)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels, 'Previsto': predictions2_labels})  
p.head(10)

Real  Previsto
0     1         1
1     1         1
2     1         1
3     1         1
4     1         1
5     1         1
6     1         1
7     1         1
8     1         1
9     1         1

In [32]:
#avaliando o modelo 
print('Matriz de Confusão\n', metrics.confusion_matrix(test_labels, predictions2_labels)) 
print('\nAcurácia\n', metrics.accuracy_score(test_labels, predictions2_labels)) 
print('\nPrecision\n', metrics.precision_score(test_labels, predictions2_labels)) 
print('\nRecall\n', metrics.recall_score(test_labels, predictions2_labels)) 

print('\nAUCROC\n', metrics.roc_auc_score(test_labels, predictions2_labels))

Matriz de Confusão
 [[133   6]
 [ 43   5]]

Acurácia
 0.7379679144385026

Precision
 0.7556818181818182

Recall
 0.9568345323741008

AUCROC
 0.5305005995203838


## WINE - KMEANS

In [49]:
dfWine = pd.read_csv("wine.csv")

In [50]:
dfWine.head(10)

class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   
5      1    14.20        1.76  2.45               15.2        112   
6      1    14.39        1.87  2.45               14.6         96   
7      1    14.06        2.15  2.61               17.6        121   
8      1    14.83        1.64  2.17               14.0         97   
9      1    13.86        1.35  2.27               16.0         98   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   
5           3.27        3.39                  0.34             1.97   
6           2.50        2.52                  0.30             1.98   
7           2.60        2.51                  0.31             1.25   
8           2.80        2.98                  0.29             1.98   
9           2.98        3.15                  0.22             1.85   

   Color_intensity   Hue  OD280%2FOD315_of_diluted_wines  Proline  
0             5.64  1.04                            3.92     1065  
1             4.38  1.05                            3.40     1050  
2             5.68  1.03                            3.17     1185  
3             7.80  0.86                            3.45     1480  
4             4.32  1.04                            2.93      735  
5             6.75  1.05                            2.85     1450  
6             5.25  1.02                            3.58     1290  
7             5.05  1.06                            3.58     1295  
8             5.20  1.08                            2.85     1045  
9             7.22  1.01                            3.55     1045

In [51]:
dfWine.shape

(178, 14)

In [52]:
dfWine['class'].unique()

array([1, 2, 3], dtype=int64)

In [53]:
dfWine.describe()

class     Alcohol  Malic_acid         Ash  Alcalinity_of_ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total_phenols  Flavanoids  Nonflavanoid_phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color_intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280%2FOD315_of_diluted_wines      Proline  
count                      178.000000   178.000000  
mean                         2.611685   746.893258  
std                          0.709990   314.907474  
min                          1.270000   278.000000  
25%                          1.937500   500.500000  
50%                          2.780000   673.500000  
75%                          3.170000   985.000000  
max                          4.000000  1680.000000

In [54]:
dfWine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
class                             178 non-null int64
Alcohol                           178 non-null float64
Malic_acid                        178 non-null float64
Ash                               178 non-null float64
Alcalinity_of_ash                 178 non-null float64
Magnesium                         178 non-null int64
Total_phenols                     178 non-null float64
Flavanoids                        178 non-null float64
Nonflavanoid_phenols              178 non-null float64
Proanthocyanins                   178 non-null float64
Color_intensity                   178 non-null float64
Hue                               178 non-null float64
OD280%2FOD315_of_diluted_wines    178 non-null float64
Proline                           178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.5 KB


In [55]:
labelWine = np.array(dfWine['class'])

dfWine = dfWine.drop('class', axis=1)
dataWine = np.array(dfWine)

In [56]:
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(dataWine, labelWine, test_size = 0.25, random_state = 42)

In [57]:
# importar o modelo de KMeans
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters = 3, random_state = 42)
 
# treinando o modelo no conjunto de dados de treino
clustering.fit(train_data);

In [58]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions1_labels = clustering.predict(test_data)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels, 'Previsto': predictions1_labels})  
p.head(10)

Real  Previsto
0     1         2
1     1         0
2     3         1
3     1         0
4     2         1
5     1         0
6     2         1
7     3         2
8     2         2
9     3         2

In [59]:
#avaliando o modelo

print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data, predictions1_labels)) 
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data, predictions1_labels)) 

print('\nMatriz de Contingência\n', metrics.cluster.contingency_matrix(test_labels, predictions1_labels)) 
print('\nMutual information\n', metrics.mutual_info_score(test_labels, predictions1_labels)) 

Coeficiente de Silhueta
 0.5519241838976592

Davies-Bouldin Score
 0.5415115100039726

Matriz de Contingência
 [[13  0  2]
 [ 0 12  6]
 [ 0  5  7]]

Mutual information
 0.526053317723497


D:\Users\elain\Anaconda3\lib\site-packages\sklearn\metrics\cluster\unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances
